translations/ui-bulk-edit/en.json

@dltj could you update translations, please

UIBULKED-2 Update translation

---

.eslintrc
CHANGELOG.md
src/BulkEdit.js
src/BulkEdit.test.js
src/BulkEditList/BulkEditList.js
src/BulkEditList/BulkEditListContainer.js
translations/ui-bulk-edit/en.json

https://issues.folio.org/browse/UIBULKED-1
While it's helpful for reviewers to help identify …

UIBULKED-1: add landing page

---

CHANGELOG.md
translations/ui-bulk-edit/en.json

https://issues.folio.org/browse/UIBULKED-23 …

UIBULKED-23 Add "Drop to continue" label to the Drag and drop area

---

CHANGELOG.md
src/components/BulkEditList/BulkEditListFilters/BulkEditListFilters.js
src/components/BulkEditList/BulkEditListFilters/ListFileUploader/ListFileUploader.js
src/components/BulkEditList/BulkEditListFilters/ListFileUploader/ListFileUploader.test.js
src/components/BulkEditList/BulkEditListFilters/ListSelect/ListSelect.js
translations/ui-bulk-edit/en.json

https://issues.folio.org/browse/UIBULKED-24 …

UIBULKED-24 Link record identifier with the drag and drop area on the landing page

---

src/components/BulkEditStartModal/BulkEditStartModal.js

https://issues.folio.org/browse/UIBULKED-17 …

UIBULKED-17 DnD should not be disabled

---

src/API/useDownloadLinks.js
src/components/BulkEditActionMenu/ActionMenuGroup/ActionMenuGroup.css
src/components/BulkEditActionMenu/ActionMenuGroup/ActionMenuGroup.js
src/components/BulkEditActionMenu/BulkEditActionMenu.js
src/components/BulkEditActionMenu/BulkEditActionMenu.test.js
src/components/BulkEditList/BulkEditListFilters/BulkEditListFilters.js
src/components/ListFileUploader/ListFileUploader.js
src/constants/constants.js
translations/ui-bulk-edit/en.json

https://issues.folio.org/browse/UIBULKED-14 …

UIBULKED-14 Show columns on the preview of records matched

---

src/components/BulkEditList/BulkEditList.js
src/components/BulkEditList/BulkEditListResult/BulkEditListResult.js
src/components/BulkEditList/BulkEditListResult/Preview/Preview.js
src/components/BulkEditList/BulkEditListResult/Preview/Preview.test.js

https://issues.folio.org/browse/UIBULKED-22 …

UIBULKED-22 Completion of the bulk edit

---

CHANGELOG.md
src/API/index.js
src/API/useDownloadLinks.js
src/API/useErrorsList.js
src/API/usePreviewRecords.js
src/API/useProgressStatus.js
src/components/BulkEdit.js
src/components/BulkEditConformationModal/BulkEditConformationModal.js
src/components/BulkEditList/BulkEditList.js
src/components/BulkEditList/BulkEditListContainer.js
src/components/BulkEditList/BulkEditListFilters/BulkEditListFilters.js
src/components/BulkEditList/BulkEditListResult/BulkEditListResult.js
src/components/BulkEditList/BulkEditListResult/Preview/ErrorsAccordion/ErrorsAccordion.js
src/components/BulkEditList/BulkEditListResult/Preview/ErrorsAccordion/ErrorsAccordion.test.js
src/components/BulkEditList/BulkEditListResult/Preview/ErrorsAccordion/index.js
src/components/BulkEditList/BulkEditListResult/Preview/Preview.js
src/components/BulkEditList/BulkEditListResult/Preview/PreviewAccordion/FormattedTime.test.js
src/components/BulkEditList/BulkEditListResult/Preview/PreviewAccordion/PreviewAccordion.js
src/components/BulkEditList/BulkEditListResult/Preview/PreviewAccordion/PreviewAccordion.test.js
src/components/BulkEditStartModal/BulkEditStartModal.js
src/components/ListFileUploader/ListFileUploader.test.js
translations/ui-bulk-edit/en.json

https://issues.folio.org/browse/UIBULKED-13 …

UIBULKED-13 Populating error accordion

---

README.md
package.json

Technical Evaluation of ui-bulk-edit pilot project

---

CHANGELOG.md
package.json

https://issues.folio.org/browse/UIBULKED-48 …

UIBULKED-48: Refactor permissions

---

src/API/useDownloadLinks.js
src/API/useProgressStatus.js
src/components/BulkEditActionMenu/BulkEditActionMenu.js
src/components/BulkEditList/BulkEditList.js
src/components/BulkEditList/BulkEditListFilters/BulkEditListFilters.js
src/components/BulkEditList/BulkEditListResult/BulkEditListResult.js
src/components/BulkEditList/BulkEditListResult/BulkEditListResult.test.js
src/components/BulkEditList/BulkEditListResult/Preview/Preview.js
src/components/BulkEditList/BulkEditListResult/Preview/Preview.test.js
src/components/BulkEditList/BulkEditListResult/PreviewInitial/PreviewInitial.js
src/components/BulkEditList/BulkEditListResult/PreviewProcessed/PreviewProcessed.js
src/components/BulkEditStartModal/BulkEditStartModal.js
src/components/ProgressBar/ProgressBar.js
src/components/ProgressBar/ProgressBar.test.js

https://issues.folio.org/browse/UIBULKED-39 …

UIBULKED-39 Filename should not be changed in background when new file was uploaded

---

package.json
src/components/BulkEdit.test.js
src/components/BulkEditList/BulkEditList.js

Comments cleanup

---

src/components/BulkEdit.test.js
src/components/BulkEditList/BulkEditListFilters/BulkEditListFilters.js
src/constants/constants.js
src/constants/optionsRecordIdentifiers.js
translations/ui-bulk-edit/en.json

https://issues.folio.org/browse/UIBULKED-28 …

UIBULKED-28 Replace checkboxes with radio buttons on the lading page

---

CHANGELOG.md
package.json
src/API/usePreviewRecords.js
src/components/BulkEdit.test.js
src/components/BulkEditActionMenu/BulkEditActionMenu.js
src/components/BulkEditActionMenu/BulkEditActionMenu.test.js
src/components/BulkEditConformationModal/BulkEditConformationModal.test.js
src/components/BulkEditList/BulkEditListFilters/BulkEditListFilters.js
src/components/BulkEditList/BulkEditListResult/BulkEditListResult.test.js
src/components/BulkEditList/BulkEditListResult/Preview/Preview.js
src/components/BulkEditList/BulkEditListResult/Preview/PreviewAccordion/PreviewAccordion.js
src/components/BulkEditList/BulkEditListResult/Preview/PreviewAccordion/PreviewAccordion.test.js
src/components/BulkEditList/BulkEditListResult/PreviewInitial/PreviewInitial.js
src/components/BulkEditList/BulkEditListResult/PreviewProcessed/PreviewProcessed.js
src/components/BulkEditStartModal/BulkEditStartModal.js
src/components/BulkEditStartModal/BulkEditStartModal.test.js
src/constants/constants.js
src/constants/optionsRecordIdentifiers.js
src/hooks/index.js

https://issues.folio.org/browse/UIBULKED-33 …

UIBULKED-56: Change bulk-edit preview endpoint

---

CHANGELOG.md
package.json
src/API/useErrorsList.js
src/components/BulkEditList/BulkEditList.js

https://issues.folio.org/browse/UIBULKED-32 …

UIBULKED-32 Error accordion - Items

---

src/components/BulkEditActionMenu/BulkEditActionMenu.js

https://issues.folio.org/browse/UIBULKED-33 …

UIBULKED-33: Starting bulk edit - in app approach

---

src/components/BulkEditList/BulkEditList.js
src/constants/constants.js
translations/ui-bulk-edit/en.json

https://issues.folio.org/browse/UIBULKED-34 …

UIBULKED-34: In-app bulk edit form

---

CHANGELOG.md
src/components/BulkEditActionMenu/BulkEditActionMenu.js
src/components/BulkEditStartModal/BulkEditStartModal.js
src/components/ProgressBar/ProgressBar.js

https://issues.folio.org/browse/UIBULKED-36 …

UIBULKED-36: Completion of the in-app bulk edit

---

CHANGELOG.md
src/components/BulkEditActionMenu/BulkEditActionMenu.js

https://issues.folio.org/browse/UIBULKED-59 …

UIBULKED-59 CSV and In app bulk edit permissions

---

package.json
src/API/useDownloadLinks.js
src/API/useErrorsList.js
src/API/useProgressStatus.js
src/components/BulkEditActionMenu/BulkEditActionMenu.js
src/components/BulkEditList/BulkEditList.js
src/components/BulkEditList/BulkEditListFilters/BulkEditListFilters.js
src/components/BulkEditList/BulkEditListResult/BulkEditInApp/BulkEditInApp.js
src/components/BulkEditList/BulkEditListResult/BulkEditListResult.js
src/components/BulkEditList/BulkEditListResult/BulkEditListResult.test.js
src/components/BulkEditStartModal/BulkEditStartModal.js
src/components/ProgressBar/ProgressBar.js
src/components/modals/BulkEditConformationModal/BulkEditConformationModal.js
src/components/modals/PreviewModal/PreviewModal.js
src/components/modals/PreviewModal/PreviewModal.test.js
src/constants/constants.js
translations/ui-bulk-edit/en.json

Progress bar for uploading identifier files and retrieving relevant data
https://issues.folio.org/browse/UIBULKED-66 …

UIBULKED-66: Progress bar for uploading identifier files and retrieving relevant data

---

CHANGELOG.md
src/API/useDownloadLinks.js
src/components/BulkEdit.test.js
src/components/BulkEditList/BulkEditList.js
src/components/BulkEditList/BulkEditList.test.js
src/components/BulkEditList/BulkEditListFilters/BulkEditListFilters.js
src/components/BulkEditList/BulkEditListResult/BulkEditInApp/BulkEditInApp.test.js
src/components/BulkEditList/BulkEditListResult/BulkEditListResult.test.js
src/components/BulkEditList/BulkEditListResult/Preview/Preview.js
src/components/BulkEditList/BulkEditListResult/Preview/Preview.test.js
src/context/RootContext.js
translations/ui-bulk-edit/en.json
translations/ui-bulk-edit/en_GB.json
translations/ui-bulk-edit/en_US.json

https://issues.folio.org/browse/UIBULKED-73 …

UIBULKED-73 New bulk edit button

---

CHANGELOG.md
src/components/BulkEditList/BulkEditListResult/BulkEditInApp/BulkEditInApp.js
src/components/BulkEditList/BulkEditListResult/BulkEditInApp/BulkEditInApp.test.js

https://issues.folio.org/browse/UIBULKED-75 …

UIBULKED-75:Enable type ahead in location look-up

---

translations/ui-bulk-edit/en.json
translations/ui-bulk-edit/en_GB.json
translations/ui-bulk-edit/en_US.json

https://issues.folio.org/browse/UIBULKED-68 …

UIBULKED-68: Changes to the Bulk edit left pane

---

CHANGELOG.md
src/components/BulkEditList/BulkEditList.js

https://issues.folio.org/browse/UIBULKED-78 …

UIBULKED-78 Clicking on Bulk Edit app icon does not fully rest the screen

---

CHANGELOG.md
src/components/BulkEditList/BulkEditList.js
src/components/BulkEditList/BulkEditListResult/Preview/ErrorsAccordion/ErrorsAccordion.js
src/components/BulkEditList/BulkEditListResult/Preview/ErrorsAccordion/ErrorsAccordion.test.js
src/components/BulkEditList/BulkEditListResult/Preview/Preview.js
src/components/BulkEditList/BulkEditListResult/Preview/Preview.test.js
src/components/BulkEditList/BulkEditListResult/Preview/PreviewAccordion/PreviewAccordion.js
src/components/BulkEditList/BulkEditListResult/Preview/PreviewAccordion/PreviewAccordion.test.js
translations/ui-bulk-edit/en.json
translations/ui-bulk-edit/en_GB.json
translations/ui-bulk-edit/en_US.json

https://issues.folio.org/browse/UIBULKED-100 …

UIBULKED-100: Matched records label cleanup - Morning Glory

---

CHANGELOG.md
src/components/BulkEditStartModal/BulkEditStartModal.js
src/components/BulkEditStartModal/BulkEditStartModal.test.js

https://issues.folio.org/browse/UIBULKED-89 …

UIBULKED-89 The name of previously uploaded file is not reset when user clicks Cancel button on the Confirmation modal

---

CHANGELOG.md
src/components/BulkEditList/BulkEditListFilters/BulkEditListFilters.js
src/components/modals/BulkEditConformationModal/BulkEditConformationModal.js
src/components/modals/PreviewModal/PreviewModal.js

https://issues.folio.org/browse/UIBULKED-131 …

UIBULKED-131 Increase maximal upload file size

---

CHANGELOG.md
package.json

https://issues.folio.org/browse/UIBULKED-64 …

UIBULKED-64 replace babel-eslint with @babel/eslint-parser

---

CHANGELOG.md
translations/ui-bulk-edit/en.json
translations/ui-bulk-edit/en_GB.json
translations/ui-bulk-edit/en_US.json

https://issues.folio.org/browse/UIBULKED-132 …

UIBULKED-132 Rename "Save and close" button to "Commit changes"

---

CHANGELOG.md
src/API/useProgressStatus.js
src/components/ProgressBar/ProgressBar.css
src/components/ProgressBar/ProgressBar.js

https://issues.folio.org/browse/UIBULKED-130 …

UIBULKED-130 Progress bar blinks (reloads) on the first run

---

.babelrc
.eslintrc
package.json
src/API/index.js
src/API/useJob.js
src/API/usePreviewRecords.js
src/API/useProgressStatus.js
src/components/BulkEdit.js
src/components/BulkEditActionMenu/BulkEditActionMenu.js
src/components/BulkEditActionMenu/BulkEditActionMenu.test.js
src/components/BulkEditList/BulkEditList.js
src/components/BulkEditList/BulkEditList.test.js
src/components/BulkEditList/BulkEditListFilters/BulkEditListFilters.js
src/components/BulkEditList/BulkEditListResult/BulkEditInApp/BulkEditInApp.js
src/components/BulkEditList/BulkEditListResult/BulkEditListResult.test.js
src/components/BulkEditList/BulkEditListResult/Preview/PreviewAccordion/PreviewAccordion.js
src/components/BulkEditList/BulkEditListResult/Preview/PreviewAccordion/PreviewAccordion.test.js
src/components/BulkEditList/BulkEditListResult/PreviewInitial/PreviewInitial.js
src/components/BulkEditList/BulkEditListResult/PreviewProcessed/PreviewProcessed.js
src/components/ProgressBar/ProgressBar.test.js
src/components/modals/PreviewModal/PreviewModal.js
src/constants/constants.js
src/constants/formatters.js
src/hooks/useInAppColumnsInfo.js

https://issues.folio.org/browse/UIBULKED-126
- Replaced columns managment from URL to LocalStorage
- Remove firing queries on focus switching (now it's firing if required only)
- Moved to separate hook logic related to columns in inApp approach 
- Fix eslint problems with new @babel/eslint-parser (previously it wasn't working)
- Moved all statuses, formatters, etc to constants
- Do PRs …

UIBULKED-126 Refactor a way of loading and showing data for In app aproach

---

CHANGELOG.md
package.json
src/API/useInAppUpload.js

[UIBULKED-140](https://issues.folio.org/browse/UIBULKED-140) …

UIBULKED-140: Update ITEMS content update

---

CHANGELOG.md
package.json
src/API/useInAppUpload.js
src/components/BulkEditActionMenu/BulkEditActionMenu.js
src/hooks/useBulkPermissions.js

https://issues.folio.org/browse/UIBULKED-104 …

UIBULKED-104 Bulk edit user records - in app permission -landing page

---

CHANGELOG.md
package.json

https://issues.folio.org/browse/UIBULKED-125 …

UIBULKED-125 User-records - commit changes - in app

---

CHANGELOG.md
package.json
src/components/modals/PreviewModal/PreviewModal.js
src/components/modals/PreviewModal/PreviewModal.test.js
src/hooks/useInAppColumnsInfo.js

[UIBULKED-124](https://issues.folio.org/browse/UIBULKED-124), [UIBULKED-124](https://issues.folio.org/browse/UIBULKED-124) …

UIBULKED-129: Preserve column selection from preview to Are you sure? form and confirmation page

---

src/API/useInAppUpload.js
src/components/BulkEditList/BulkEditListResult/BulkEditInApp/forms/HoldingsForm/HoldingsForm.js
src/components/BulkEditList/BulkEditListResult/BulkEditInApp/forms/ItemForm/ItemForm.js
src/components/BulkEditList/BulkEditListResult/BulkEditInApp/forms/utils.js

[UIBULKED-115](https://issues.folio.org/browse/UIBULKED-115) …

UIBULKED-115: In-app bulk edit form - holdings location

---

CHANGELOG.md
src/components/modals/PreviewModal/PreviewModal.js
src/components/modals/PreviewModal/PreviewModalFooter.js

https://issues.folio.org/browse/UIBULKED-143 …

UIBULKED-143 Prevent user from clicking on "Commit changes" in "Are you sure" form until preview is completed

---

CHANGELOG.md
src/API/useInAppUpload.js
src/components/BulkEditStartModal/BulkEditStartModal.js
src/components/modals/PreviewModal/PreviewModal.js
src/components/modals/PreviewModal/PreviewModalFooter.js

https://issues.folio.org/browse/UIBULKED-149 …

UIBULKED-149 The progressbar freezes when file with edited Users records uploading

---

CHANGELOG.md
src/components/BulkEditList/BulkEditList.js
src/components/BulkEditList/BulkEditListResult/BulkEditListResult.test.js
src/components/BulkEditList/BulkEditListResult/PreviewProcessed/PreviewProcessed.js
src/components/BulkEditStartModal/BulkEditStartModal.js
src/components/modals/BulkEditConformationModal/BulkEditConformationModal.js
src/components/modals/BulkEditConformationModal/BulkEditConformationModal.test.js

https://issues.folio.org/browse/UIBULKED-133 …

UIBULKED-133 The Bulk edit modal displays previous filename starting Bulk Edit from confirmation screen

---

CHANGELOG.md
src/components/BulkEditList/BulkEditListFilters/BulkEditListFilters.js
src/components/BulkEditList/BulkEditListResult/BulkEditInApp/forms/HoldingsForm/HoldingsForm.js

UIBULKED-139: Preview of matched records reloads when User select any other Identifier type

---

CHANGELOG.md
src/components/modals/PreviewModal/PreviewModal.js

https://issues.folio.org/browse/UIBULKED-150 …

UIBULKED-150 Remove record count on the Are you sure? form until the loading of data is done

---

CHANGELOG.md
src/components/BulkEditList/BulkEditListResult/BulkEditInApp/BulkEditInApp.test.js
src/constants/constants.js
src/hooks/useFormValid.js
translations/ui-bulk-edit/en.json
translations/ui-bulk-edit/en_US.json

https://issues.folio.org/browse/UIBULKED-147 …

UIBULKED-147 The "Options" dropdown on the in-app bulk edit form does not contain placeholder

---

CHANGELOG.md
package.json

https://issues.folio.org/browse/UIBULKED-152 …

UIBULKED-152 @babel/eslint-parser is incorrectly listed as a direct dependency

---

package.json

[UIBULKED-172](https://issues.folio.org/browse/UIBULKED-172) …

UIBULKED-172: Missing bulk edit Inventory-holdings UI permissions

---

CHANGELOG.md
src/constants/constants.js

400 Error when user change Item's status to "Intellectual item" via Bulk edit
https://issues.folio.org/browse/UIBULKED-175 …

UIBULKED-175: 400 Error when user change Item's status to "Intellectual item" via Bulk edit

---

CHANGELOG.md
src/components/BulkEditList/BulkEditList.js
src/components/BulkEditList/BulkEditListResult/BulkEditInApp/forms/HoldingsForm/HoldingsForm.js
src/components/modals/PreviewModal/PreviewModal.js

https://issues.folio.org/browse/UIBULKED-170 …

UIBULKED-170 Something went wrong" appears after modifying Holdings record

---

CHANGELOG.md
src/components/BulkEditList/BulkEditListResult/BulkEditInApp/forms/HoldingsForm/HoldingsForm.js
src/components/BulkEditList/BulkEditListResult/BulkEditInApp/forms/ItemForm/ItemForm.js
src/components/BulkEditList/BulkEditListResult/BulkEditInApp/forms/UserForm/UserForm.js
src/components/BulkEditList/BulkEditListResult/BulkEditInApp/forms/utils.js

https://issues.folio.org/browse/UIBULKED-163 …

UIBULKED-163 User can add more rows than supported options

---

CHANGELOG.md
package.json
src/components/BulkEdit.test.js
src/components/BulkEditList/BulkEditList.js
src/components/BulkEditList/BulkEditListFilters/BulkEditListFilters.js
src/components/BulkEditList/BulkEditListFilters/LogsFilters/LogsFilters.js
src/components/BulkEditList/BulkEditListFilters/LogsFilters/LogsFilters.test.js
src/components/BulkEditList/BulkEditListResult/NoResultsMessage/NoResultsMessage.js
src/constants/constants.js
src/hooks/UseLocationFilters.js
src/hooks/index.js
src/hooks/useBulkPermissions.js
translations/ui-bulk-edit/en.json
translations/ui-bulk-edit/en_GB.json
translations/ui-bulk-edit/en_US.json

[UIBULKED-158](https://issues.folio.org/browse/UIBULKED-158) …

UIBULKED-158: Add search and filters pane to bulk edit logs

---

CHANGELOG.md
translations/ui-bulk-edit/en.json

https://issues.folio.org/browse/UIBULKED-177 …

UIBULKED-177 permissions from package.json are missing in translations files

---

CHANGELOG.md
translations/ui-bulk-edit/en.json

UIBULKED-177 modify changelog.md

---

CHANGELOG.md
package.json

Release 2.1.1

---

CHANGELOG.md
src/components/modals/PreviewModal/PreviewModal.js
src/components/modals/PreviewModal/PreviewModal.test.js

https://issues.folio.org/browse/UIBULKED-176 …

UIBULKED-176 Loader disappears before data is loaded

---

CHANGELOG.md
src/components/BulkEditList/BulkEditList.js

https://issues.folio.org/browse/UIBULKED-186 …

UIBULKED-186 Hide actions button on Logs form

---

CHANGELOG.md
src/components/modals/PreviewModal/PreviewModal.js
src/components/modals/PreviewModal/PreviewModalFooter.js

https://issues.folio.org/browse/UIBULKED-202 …

UIBULKED-202 The "Commit changes" button is enabled before Preview of records to be changed displayed

---

CHANGELOG.md
src/components/BulkEditList/BulkEditListResult/BulkEditInApp/BulkEditInApp.test.js
src/components/BulkEditList/BulkEditListResult/BulkEditListResult.test.js
src/hooks/usePulling.test.js

[UIBULKED-184](https://issues.folio.org/browse/UIBULKED-184) …

UIBULKED-184: Increase unit test code coverage for ui-bulk-edit

---

CHANGELOG.md
translations/ui-bulk-edit/en.json

https://issues.folio.org/browse/UIBULKED-200 …

UIBULKED-200: some translations for permissions are missing

---

CHANGELOG.md
src/components/RetrievedDataList/RetrievedDataList.js

https://issues.folio.org/browse/UIBULKED-180 …

UIBULKED-180 Paginate through results sets

---

CHANGELOG.md
src/API/useFileUpload.js
src/API/useProgressStatus.js
src/components/BulkEditList/BulkEditList.test.js
src/components/BulkEditList/BulkEditListFilters/BulkEditListFilters.js
src/components/BulkEditList/BulkEditListResult/PreviewInitial/PreviewInitial.js
src/components/BulkEditStartModal/BulkEditStartModal.js

https://issues.folio.org/browse/UIBULKED-206 …

UIBULKED-206 [FE] Query search isn't working

---

CHANGELOG.md
src/components/BulkEditList/BulkEditList.js

"Users" record type is selected by default with only In-app permissions
[UIBULKED-219](https://issues.folio.org/browse/UIBULKED-219)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of …

UIBULKED-219: "Users" record type is selected by default with only In-app permissions

---

CHANGELOG.md
src/API/useProgressStatus.js

[UIBULKED-230](https://issues.folio.org/browse/UIBULKED-230) …

UIBULKED-230: Missing spinner for long executing query

---

src/API/useProgressStatus.js

[UIBULKED-229](https://issues.folio.org/browse/UIBULKED-229) …

UIBULKED-230: Query search doesn't work twice in a row

---

CHANGELOG.md
package.json
tsconfig.json

https://issues.folio.org/browse/UIBULKED-221 …

UIBULKED-221 [FE] [TS] Add config files for TypeScript supporting

---

CHANGELOG.md
package.json
src/components/BulkEditList/BulkEditListFilters/BulkEditListFilters.js
src/components/BulkEditList/BulkEditListFilters/QueryTextArea/QueryTextArea.js
src/hooks/useBulkPermissions.js

https://issues.folio.org/browse/UIBULKED-164 …

UIBULKED-164 Query tab permissions

---

package.json
src/hooks/api/useBulkEditLogs/useBulkEditLogs.js

UIBULKED-196 permissions

---

src/components/BulkEditList/BulkEditListResult/BulkEditManualUploadModal/BulkEditManualUploadModal.js

UIBULKED-196 fix csv manual upload

---

package.json

UIBULKED-164 query tab backend permissions

---

package.json
src/components/BulkEditList/BulkEditList.js
src/components/BulkEditList/BulkEditListFilters/BulkEditListFilters.js
src/components/BulkEditList/BulkEditListResult/BulkEditInAppPreviewModal/BulkEditInAppPreviewModal.js
src/hooks/api/useBulkOperationStart.js
src/hooks/api/usePatronGroup.js
src/hooks/api/useUpload.js
translations/ui-bulk-edit/en.json

UIBULKED-196 bulk-edit adjustments and fixes

---

CHANGELOG.md
src/components/BulkEditLogs/BulkEditLogs.js
src/components/BulkEditLogs/BulkEditLogsActions/BulkEditLogsActions.js
src/components/BulkEditLogs/BulkEditLogsActions/BulkEditLogsActions.test.js
src/hooks/useBulkPermissions.js

https://issues.folio.org/browse/UIBULKED-253 …

UIBULKED-253 User without "Users: Can view user profile" permission can download file from "Logs" tab

---

CHANGELOG.md
package.json

Release 3.0.2

---

CHANGELOG.md
src/components/ProgressBar/ProgressBar.js
src/components/ProgressBar/utils.js
src/components/ProgressBar/utils.test.js

https://issues.folio.org/browse/UIBULKED-266 …

UIBULKED-266 Confirmation screen is missing for completed with errors operations

---

CHANGELOG.md
src/components/BulkEditActionMenu/BulkEditActionMenu.js
src/hooks/api/useRecordsPreview.js

https://issues.folio.org/browse/UIBULKED-265 …

UIBULKED-265 Columns on the 'Are you sure' form are mixed in case simultaneously running jobs

---

CHANGELOG.md
src/constants/columns.js
translations/ui-bulk-edit/en.json

https://issues.folio.org/browse/UIBULKED-261 …

UIBULKED-261 Replace UUID with HRID on Logs

---

src/components/BulkEditList/BulkEditListFilters/BulkEditListFilters.js

https://issues.folio.org/browse/UIBULKED-165 …

UIBULKED-165 covering all disabling cases of query-plugin btn

---

CHANGELOG.md
src/components/BulkEditList/BulkEditListFilters/BulkEditListFilters.js
src/components/BulkEditList/BulkEditListResult/NoResultsMessage/NoResultsMessage.js
src/components/ProgressBar/ProgressBar.js
src/components/ProgressBar/ProgressBar.test.js
translations/ui-bulk-edit/en.json

https://issues.folio.org/browse/UIBULKED-260 …

UIBULKED-260 "Something went wrong" error message appears when search by Query is done by no-existing or no-result value

---

CHANGELOG.md
src/constants/files.js

https://issues.folio.org/browse/UIBULKED-264 …

UIBULKED-264 "Download matched records (CSV)" option is enabled on the confirmation screen

---

CHANGELOG.md
src/components/BulkEditList/BulkEditListResult/BulkEditInApp/BulkEditInApp.test.js
src/components/BulkEditList/BulkEditListResult/BulkEditInApp/ContentUpdatesForm/ActionsRow.js

UIBULKED-262 fix datepicker

---

src/typings/stripes/stripes-components/lib/MetaSection/MetaSection.d.ts

UIBULKED-222 add User declaration to MetaSection.d.ts

---

CHANGELOG.md
package.json

Release v3.0.5

---

CHANGELOG.md
src/components/BulkEditList/BulkEditListResult/BulkEditInApp/ContentUpdatesForm/ActionsRow.js
src/components/BulkEditList/BulkEditListResult/BulkEditInApp/ContentUpdatesForm/helpers.js
src/constants/selectOptions.js
translations/ui-bulk-edit/en.json

[UIBULKED-244](https://issues.folio.org/browse/UIBULKED-244) …

UIBULKED-244: Add Suppress from discovery option

---

CHANGELOG.md
src/components/BulkEditList/BulkEditList.js
src/components/ProgressBar/ProgressBar.js
src/components/ProgressBar/ProgressBar.test.js
translations/ui-bulk-edit/en.json

[UIBULKED-269](https://issues.folio.org/browse/UIBULKED-269) …

UIBULKED-269: Modify text when updates are committed

---

src/components/BulkEditList/BulkEditListResult/BulkEditInAppPreviewModal/BulkEditInAppPreviewModal.js

UIBULKED-283: Make column names sticky

---

CHANGELOG.md
src/components/BulkEditLogs/BulkEditLogs.js
src/constants/core.js

https://issues.folio.org/browse/UIBULKED-294 …

UIBULKED-294 Log tab paginates by 50 records instead of 100

---

CHANGELOG.md
src/components/BulkEditList/BulkEditList.js
src/components/BulkEditList/BulkEditListResult/BulkEditManualUploadModal/BulkEditManualUploadModal.js
src/hooks/api/useUpload.js

https://issues.folio.org/browse/UIBULKED-308 …

UIBULKED-308 CSV: Cancel button doesn't stop file uploading

---

CHANGELOG.md
src/components/BulkEditList/BulkEditListResult/BulkEditInApp/ContentUpdatesForm/ContentUpdatesForm.js
src/components/BulkEditList/BulkEditListResult/BulkEditInApp/ContentUpdatesForm/helpers.js
src/components/BulkEditList/BulkEditListResult/BulkEditInApp/ContentUpdatesForm/helpers.test.js
src/constants/inAppActions.js
translations/ui-bulk-edit/en.json

https://issues.folio.org/browse/UIBULKED-301 …

UIBULKED-301 Bulk edit actions for notes - find and replace or remove

---

src/components/BulkEditList/BulkEditListResult/BulkEditInApp/BulkEditInApp.js
src/components/BulkEditList/BulkEditListResult/BulkEditInApp/ContentUpdatesForm/ValuesColumn.js
src/components/BulkEditList/BulkEditListResult/BulkEditInApp/ContentUpdatesForm/helpers.js
src/components/BulkEditList/BulkEditListResult/BulkEditInApp/ContentUpdatesForm/helpers.test.js
src/hooks/api/useItemNotes.js
src/hooks/api/useLoanTypes.js
src/hooks/api/usePatronGroup.js

Fixed: 
- When Temporary item location is selected - SWW error is present
- Loan types, patron groups, item notes - requested data all the time. After fix it depends on selected records type
https://issues.folio.org/browse/UIBULKED-301
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing …

UIBULKED-301 fix regression issues

---

CHANGELOG.md
translations/ui-bulk-edit/en.json

UIBULKED-328: Rename Actions menu option for Bulk edit (CSV) approach
[UIBULKED-328](https://issues.folio.org/browse/UIBULKED-328)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule …

UIBULKED-328: Rename Actions menu option for Bulk edit (CSV) approach

---

CHANGELOG.md
package.json
src/components/BulkEditActionMenu/BulkEditActionMenu.js
src/components/BulkEditList/BulkEditListFilters/BulkEditListFilters.js
src/components/BulkEditList/BulkEditListFilters/utils/getIsDisabledByPerm.js
src/components/BulkEditList/BulkEditListFilters/utils/getIsDisabledByPerm.test.js
src/hooks/useBulkPermissions.js
src/utils/filters.js

[UIBULKED-322](https://issues.folio.org/browse/UIBULKED-322) …

UIBULKED-322: Permissions for editing User records

---

CHANGELOG.md
src/components/BulkEditList/BulkEditListFilters/LogsFilters/LogsFilters.js
src/components/BulkEditList/BulkEditListFilters/LogsFilters/LogsFilters.test.js
src/constants/core.js
src/hooks/api/useBulkOperationUsers.js
translations/ui-bulk-edit/en.json

Added User filter for Bulk Edit Logs tab 
https://issues.folio.org/browse/UIBULKED-318
While …

UIBULKED-318 Add User filter to Logs tab

---

.eslintrc
src/components/BulkEdit.test.js
src/components/BulkEditList/BulkEditListFilters/BulkEditListFilters.js
src/components/BulkEditList/BulkEditListFilters/LogsFilters/LogsFilters.js

Wrong message on Bulk edit main page without View Inventory/Users permissions
[UIBULKED-340](https://issues.folio.org/browse/UIBULKED-340)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of …

UIBULKED-340: Wrong message on Bulk edit main page without View Inventory/Users permissions

---

CHANGELOG.md
src/components/BulkEditList/BulkEditListResult/BulkEditManualUploadModal/BulkEditManualUploadModal.js
src/hooks/api/useBulkOperationDelete.js
translations/ui-bulk-edit/en.json

CSV: On cancel button click uploaded file should be deleted
[UIBULKED-312](https://issues.folio.org/browse/UIBULKED-312) …

UIBULKED-312: CSV: On cancel button click uploaded file should be deleted

---

CHANGELOG.md
src/components/BulkEditActionMenu/BulkEditActionMenu.js
src/constants/files.js

[UIBULKED-343](https://issues.folio.org/browse/UIBULKED-343) …

UIBULKED-343: Refactor logic for downloading file from actions menu

---

CHANGELOG.md
src/components/BulkEditActionMenu/BulkEditActionMenu.js
src/utils/mappers/mappers.js

https://issues.folio.org/browse/UIBULKED-341 …

UIBULKED-341 Separate Item notes in different columns based on the note type

---

CHANGELOG.md
translations/ui-bulk-edit/en.json

https://issues.folio.org/browse/UIBULKED-276 …

UIBULKED-276 Rename "Instance" column for holdings records preview

---

CHANGELOG.md
translations/ui-bulk-edit/en.json

Changed based on BE requiremets. In scope of [UIBULKED-276](https://issues.folio.org/browse/UIBULKED-276)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …

UIBULKED-276 change translation key for Instance column

---

CHANGELOG.md
src/hooks/api/useBulkOperationUsers.js

Removed limit from qury, because BE expecting null here to return all values.
https://issues.folio.org/browse/UIBULKED-373 …

UIBULKED-373 "User" dropdown doesn't include Users recently run bulk edit jobs

---

CHANGELOG.md
translations/ui-bulk-edit/en.json

[UIBULKED-356](https://issues.folio.org/browse/UIBULKED-356) …

UIBULKED-356: Separate holdings notes by note type

---

CHANGELOG.md
src/constants/selectOptions.js

[UIBULKED-347](https://issues.folio.org/browse/UIBULKED-347) …

UIBULKED-347: Group holdings record properties using optgroup component

---

src/utils/sortAlphabetically.js
src/utils/sortAlphabetically.test.js

[UIBULKED-375](https://issues.folio.org/browse/UIBULKED-375)
Small fix for implemented logic
https://github.com/folio-org/ui-bulk-edit/assets/72550466/d0174b38-795b-4cab-8946-d24c873edf87

UIBULKED-375: Localize alphabetical order of Bulk edit elements

---

translations/ui-bulk-edit/en.json

[UIBULKED-382](https://issues.folio.org/browse/UIBULKED-382)
It is small update for missed key translation

UIBULKED-382: Update Item record column names

---

CHANGELOG.md
translations/ui-bulk-edit/en.json

[UIBULKED-393](https://issues.folio.org/browse/UIBULKED-393)
Here we added new filter to Log tab
https://github.com/folio-org/ui-bulk-edit/assets/72550466/95e8f028-a3dc-4de0-a686-0b50fb9a4253

UIBULKED-393: Add Inventory - instances filter to the Logs tab

---

src/components/BulkEditLogs/BulkEditLogsActions/BulkEditLogsActions.js

[UIBULKED-387](https://issues.folio.org/browse/UIBULKED-387)
Here small fix permissions rule

UIBULKED-387: Permissions for bulk editing instances

---

src/constants/columns.js
src/utils/mappers/mappers.js

[UIBULKED-364](https://issues.folio.org/browse/UIBULKED-364)
Here small updated to implemented and merged story. We added format time for `Cataloged date` column.

UIBULKED-364: Instance records - preview of matching records

---

src/components/BulkEditList/BulkEditListSidebar/IdentifierTab/IdentifierTab.js

https://folio-org.atlassian.net/browse/UIBULKED-210 …

UIBULKED-210 fix handling error message

---

CHANGELOG.md
translations/ui-bulk-edit/en.json

https://folio-org.atlassian.net/browse/UIBULKED-398
Here we added new translation key for Item column

UIBULKED-398: Add Holdings column to Item record columns

---

src/components/BulkEditList/BulkEditListSidebar/QueryTab/QueryTab.js
translations/ui-bulk-edit/en.json

https://folio-org.atlassian.net/browse/UIBULKED-414
It's small fix for existing logic

UIBULKED-414: Query search results display

---

CHANGELOG.md
src/components/BulkEditList/BulkEditListSidebar/QueryTab/QueryTab.js

Set maximum limit for query builder plugin.

UIBULKED-451 Set Maximum Limit for Bulk Edit

---

CHANGELOG.md
src/components/BulkEditPane/BulkEditListResult/BulkEditListResult.test.js
src/components/BulkEditPane/BulkEditListResult/PreviewContainer/PreviewContainer.js
src/hooks/api/useQueryPlugin.js

After this PR merged fqlQuery will be replaces with user-friendly variant of query which will be show on bulk edit preview page. Ref [UIBULKED-426](https://folio-org.atlassian.net/browse/UIBULKED-426)

UIBULKED-426 Query String Display  After Query Builder Closes

---

translations/ui-bulk-edit/en.json

UIBULKED-415 add execution query status

---

CHANGELOG.md
src/components/BulkEditPane/BulkEditIdentifiers/BulkEditIdentifiers.js
src/components/BulkEditPane/BulkEditListResult/BulkEditInApp/BulkEditInApp.js
src/components/BulkEditPane/BulkEditListResult/BulkEditInApp/BulkEditInAppTitle/BulkEditInAppTitle.css
src/components/BulkEditPane/BulkEditListResult/BulkEditInApp/BulkEditInAppTitle/BulkEditInAppTitle.js
src/components/BulkEditPane/BulkEditListResult/BulkEditInApp/ContentUpdatesForm/ContentUpdatesForm.js
src/components/BulkEditPane/BulkEditListResult/PreviewContainer/PreviewContainer.js
src/hooks/api/useHoldingsNotes.js
src/hooks/api/useItemNotes.js

After this PR merged, then on the COMMIT step of bulk edit will be update information.

UIBULKED-465 Local approach - Incorrect numbers of changed records and errors are displayed on Confirmation screen

---

CHANGELOG.md
translations/ui-bulk-edit/en.json

https://folio-org.atlassian.net/browse/UIBULKED-463
Here we add a translation key for the column.

UIBULKED-463: Update translation with new key fo columns

---

CHANGELOG.md
src/components/shared/ProgressBar/ProgressBar.js

UIBULKED-472 Fix 100% progress bar when progress is not available.

---

CHANGELOG.md
src/components/BulkEdit.test.js
src/components/BulkEditLogs/BulkEditLogs.js
src/components/BulkEditPane/BulkEditIdentifiers/BulkEditIdentifiers.js
src/components/BulkEditPane/BulkEditPane.test.js
src/components/BulkEditPane/BulkEditQuery/BulkEditQuery.js
test/jest/__mock__/stripesCore.mock.js
translations/ui-bulk-edit/en.json

https://folio-org.atlassian.net/browse/UIBULKED-455
We added TitleManager to handle titles  on different tabs.
https://github.com/folio-org/ui-bulk-edit/assets/72550466/207afbdd-80a1-4dba-bb4c-fcc4f1ef98f8

UIBULKED-455: Update HTML Page Title on Bulk Edit Tabs Page

---

src/hooks/usePreselectedValue.js

In scope of https://github.com/folio-org/ui-bulk-edit/pull/503 were updated a lot of dependencies, but based on current implementation in some cases it's not possible to fit eslint rules. This PR will rollback 1 part related to in-app update and preselecting value.

UIBULKED-454 update usePreselectedValue dependencies

---

src/components/BulkEditActionMenu/BulkEditActionMenu.js
src/components/BulkEditPane/BulkEditPane.js

UIBULKED-416 avoid action menu flush

---

CHANGELOG.md
package.json

Update permissions for download files in export manager

UIBULKED-478 Update permissions related to export manager module

---

src/components/BulkEditPane/BulkEditListResult/Preview/ElectronicAccessTable/ElectronicAcess.css

After latest updates related to CSS it's required add flex growing to ElectroicTable class

UIBULKED-458 Change styles for ElectronicAccess

---

CHANGELOG.md
src/components/BulkEditPane/BulkEditListResult/BulkEditInApp/BulkEditInApp.js
src/components/BulkEditPane/BulkEditListResult/BulkEditInApp/ContentUpdatesForm/ValuesColumn.js
src/components/BulkEditPane/BulkEditListResult/BulkEditInApp/ContentUpdatesForm/ValuesColumn.test.js
src/components/BulkEditPane/BulkEditListResult/BulkEditInApp/ContentUpdatesForm/helpers.js
src/constants/selectOptions.js
src/hooks/api/useInstanceNotes.js
translations/ui-bulk-edit/en.json

https://folio-org.atlassian.net/browse/UIBULKED-445
Here we added instance notes in bulk edit in app form
https://github.com/folio-org/ui-bulk-edit/assets/72550466/ec9767b3-bf22-41bc-9a4e-2f9f5a1b229e

UIBULKED-445: Populate Bulk Edit Form with Instance Note Types

---

CHANGELOG.md
src/components/BulkEditActionMenu/BulkEditActionMenu.js
translations/ui-bulk-edit/en.json

After this PR merged we will see new button name for Instance record type. Refs [UIBULKED-449](https://folio-org.atlassian.net/browse/UIBULKED-449)

UIBULKED-449 Navigate to FOLIO Instances Bulk Edit Screen

---

CHANGELOG.md
src/components/BulkEditPane/BulkEditListResult/Preview/ErrorsAccordion/ErrorsAccordion.js
src/components/BulkEditPane/BulkEditListResult/Preview/Preview.css
src/constants/core.js
translations/ui-bulk-edit/en.json

After this PR merged the link for error will be shown in error accordion. Refs [UIBULKED-456](https://folio-org.atlassian.net/browse/UIBULKED-456)

UIBULKED-456 Provide User-friendly Error Message for Optimistic Locking

---

CHANGELOG.md
src/components/BulkEditActionMenu/BulkEditActionMenu.js
translations/ui-bulk-edit/en.json

After this change merged, new button to bulk edit action menu will be added. Refs UIBULKED-450

UIBULKED-450 Navigate to MARC Instances Bulk Edit Screen

---

CHANGELOG.md
translations/ui-bulk-edit/en.json

https://folio-org.atlassian.net/browse/UIBULKED-496
Here we added a missed translation

UIBULKED-443: Separate Instance Notes by Note Type

---

CHANGELOG.md
package.json
src/components/BulkEditPane/BulkEditListResult/BulkEditInAppLayer/BulkEditLayer.js
src/components/BulkEditPane/BulkEditListResult/BulkEditMark/BulkEditMark.js
src/components/BulkEditPane/BulkEditListResult/BulkEditMark/BulkEditMarkForm/BulkEditMarkActionRow.js
src/components/BulkEditPane/BulkEditListResult/BulkEditMark/BulkEditMarkForm/BulkEditMarkForm.js
src/components/BulkEditPane/BulkEditListResult/BulkEditMark/BulkEditMarkForm/BulkEditMarkFormField.js
src/components/BulkEditPane/BulkEditListResult/BulkEditMark/BulkEditMarkTitle/BulkEditMarkTitle.js
src/components/BulkEditPane/BulkEditListResult/BulkEditMark/helpers.js
src/components/BulkEditPane/BulkEditListResult/BulkEditMark/helpers.test.js
src/components/BulkEditPane/BulkEditListResult/BulkEditMark/validation.js
src/components/BulkEditPane/BulkEditListResult/BulkEditMark/validation.test.js
src/components/BulkEditPane/BulkEditMarkLayer/BulkEditMarkLayer.test.js
src/components/BulkEditPane/BulkEditPane.css
src/constants/markActions.js
src/hooks/useMarkApproach.js
src/hooks/useMarkApproach.test.js
translations/ui-bulk-edit/en.json

After this PR merges, functionality related to Find + Append actions will be added for mark record. Refs [UIBULKED-482](https://folio-org.atlassian.net/browse/UIBULKED-482)

UIBULKED-482 Find (full subfield search) and Append a new subfield for MARC Instance

---

CHANGELOG.md
src/components/BulkEditPane/BulkEditListResult/BulkEditInApp/BulkEditInApp.js
src/components/BulkEditPane/BulkEditListResult/BulkEditInApp/BulkEditInApp.test.js
src/components/BulkEditPane/BulkEditListResult/BulkEditInApp/ContentUpdatesForm/ContentUpdatesForm.js
src/constants/selectOptions.js
src/hooks/api/index.js
src/utils/helpers.js

After this PR merged select component will be replaced with Selection component + group supproting. All tests were updated based on new component. Refs: [UIBULKED-440](https://folio-org.atlassian.net/browse/UIBULKED-440)

UIBULKED-440 Add Search box to Group Component

---

src/constants/columns.js
src/utils/mappers/mappers.js

In scope of https://folio-org.atlassian.net/browse/UIBULKED-381 and https://folio-org.atlassian.net/browse/MODBULKOPS-204 some columns were updated, but for some of them we should ignore time in formattin. In this PR this columns were added in exception.

UIBULKED-381 Add exceptional date columns without time

---

CHANGELOG.md
src/components/BulkEditPane/BulkEditListResult/BulkEditMark/BulkEditMarkForm/BulkEditMarkActionRow.js
src/components/BulkEditPane/BulkEditListResult/BulkEditMark/BulkEditMarkTitle/BulkEditMarkTitle.js
src/components/BulkEditPane/BulkEditPane.css

https://folio-org.atlassian.net/browse/UIBULKED-507
Here we update the logic of visualizing required fields in MARC form.
https://github.com/user-attachments/assets/c286aa34-d919-4774-b4a6-f85f1a974266

UIBULKED-507: MARC Instance - Update required field notification

---

CHANGELOG.md
src/hooks/api/useQueryPlugin.js

UIBULKED-527 include queryId to bulk-edit query request

---

.github/workflows/build-npm-release.yml
.github/workflows/build-npm.yml
src/components/BulkEditActionMenu/BulkEditActionMenu.js
src/hooks/useBulkPermissions.js

https://folio-org.atlassian.net/browse/UIBULKED-535
Small fix for existing implementations. Here I fixed issue with the wrong edit permission and changed the structure of the action menu groups

UIBULKED-535: Permissions for editing Instances with MARC source

---

package.json
src/components/BulkEditPane/BulkEditListResult/BulkEditInAppPreviewModal/BulkEditInAppPreviewModal.test.js
src/components/BulkEditPane/BulkEditListResult/BulkEditManualUploadModal/BulkEditManualUploadModal.test.js
src/components/PermissionsModal/PermissionsModal.test.js

align UI with BE permissions

---

package.json

https://folio-org.atlassian.net/browse/UIBULKED-524
Fix backend permissions

UIBULKED-524: Localize Item's and Holdings' Notes names in ECS

---

src/utils/files.js
translations/ui-bulk-edit/en.json

https://folio-org.atlassian.net/browse/UIBULKED-501
Small fix for existing implementation of downloading mrc files from logs

UIBULKED-501: Downloading .mrc file from Confirmation form

---

CHANGELOG.md
src/components/BulkEditPane/BulkEditPane.css
src/constants/selectOptions.js
translations/ui-bulk-edit/en.json

https://folio-org.atlassian.net/browse/UIBULKED-549
Here we added new option for `ITEM_STATUS` in-app bulk-edit

UIBULKED-549: Add additional item status

---

CHANGELOG.md
src/components/BulkEditPane/BulkEditListResult/BulkEditMark/validation.js
src/hooks/api/useElectronicAccessEsc.js

https://folio-org.atlassian.net/browse/UIBULKED-559
Here we updated the validation process for `subfield` input in MARC form, we are not able to pass uppercase letters here.

UIBULKED-559: Update subfield validation in MARC form

---

CHANGELOG.md
translations/ui-bulk-edit/en.json

https://folio-org.atlassian.net/browse/UIBULKED-556
Here we added a translation for the new column `Member`.

UIBULKED-558: Add translation for new "Member" column

---

CHANGELOG.md
package.json
src/components/PermissionsModal/PermissionsModal.test.js
src/hooks/useBulkPermissions.js

UIBULKED-545 Clean up permissions

---

translations/ui-bulk-edit/en.json

UIBULKED-545 align translations with permissions

---

src/hooks/useBulkPermissions.js

UIBULKED-545 fix permissions for users record

---

CHANGELOG.md
src/components/BulkEditPane/BulkEditListResult/BulkEditInApp/ContentUpdatesForm/ContentUpdatesForm.js

https://folio-org.atlassian.net/browse/UIBULKED-572
Here we added a new field `updated_tenants `for edge cases with `find and replace` action.

UIBULKED-572: Include additional field to 'actions'

---

CHANGELOG.md
src/components/BulkEditPane/BulkEditListResult/BulkEditInApp/ContentUpdatesForm/ValuesColumn.js

https://folio-org.atlassian.net/browse/UIBULKED-557
Here we added `title` for wrapped element around `select` to improve accessibility

UIBULKED-557: Add hover effect to improve text visibility in dropdowns in Bulk Edit in-app form

---

CHANGELOG.md
src/components/BulkEditPane/BulkEditListResult/BulkEditInApp/BulkEditInApp.js
src/components/BulkEditPane/BulkEditListResult/BulkEditInApp/ContentUpdatesForm/ValuesColumn.js
src/hooks/api/useBulkOperationTenants.js

https://folio-org.atlassian.net/browse/UIBULKED-575
Here we fixed logic for `ecs` calls in consortia.
Video for `ecs` env
https://github.com/user-attachments/assets/a701f26b-da50-4da9-9366-ac785b1642b6
and non-ecs env
https://github.com/user-attachments/assets/c11ea646-4f70-4266-b6b0-189cca418a63

UIBULKED-575: Fix "Something went wrong" toast notifications when starting bulk edit

---

package.json

Add missed permissions

---

CHANGELOG.md
src/components/BulkEdit.js
src/components/BulkEditProfiles/BulkEditProfileDetails.js
src/components/BulkEditProfiles/BulkEditProfileDetails.test.js
src/components/BulkEditProfiles/BulkEditProfiles.js
src/components/BulkEditProfiles/BulkEditProfiles.test.js
src/components/BulkEditProfiles/BulkEditProfilesPane.js
src/components/BulkEditProfiles/constants.js
src/hooks/api/index.js
src/hooks/api/useBulkEditProfile.js
translations/ui-bulk-edit/en.json

https://folio-org.atlassian.net/browse/UIBULKED-688
- Render profile names as router links;
- On link click, open profile details;
https://github.com/user-attachments/assets/722e77eb-d263-45d7-a9c4-407706af929f
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication …

UIBULKED-688 View 'Summary' of existing bulk edit profile

---

package.json

https://folio-org.atlassian.net/browse/UIBULKED-661

UIBULKED-661 Include BE permission in the UI set

---

CHANGELOG.md
src/components/BulkEditProfiles/BulkEditDuplicateProfile/BulkEditDuplicateProfile.js
src/components/BulkEditProfiles/BulkEditDuplicateProfile/BulkEditDuplicateProfile.test.js
src/components/BulkEditProfiles/BulkEditDuplicateProfile/index.js
src/components/BulkEditProfiles/BulkEditProfileDetails.js
src/components/BulkEditProfiles/BulkEditProfilesPane.js
translations/ui-bulk-edit/en.json

UIBULKED-660 Duplicating a Bulk Edit Profile
