folio-org/ui-bulk-edit

CHANGELOG.md
src/hooks/useBulkPermissions.js

Bulk Edit app loses state when navigating to another app and back, and remembers filename but not record type
[UIBULKED-197](https://issues.folio.org/browse/UIBULKED-197)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …

UIBULKED-197: Bulk Edit app loses state when navigating to another app and back, and remembers filename but not record type

---

CHANGELOG.md
src/components/BulkEditList/BulkEditListFilters/BulkEditListFilters.js

https://issues.folio.org/browse/UIBULKED-220 …

UIBULKED-220 Bulk edit state isn't reset to its default value when the Record type is changed

---

CHANGELOG.md
src/components/BulkEditList/BulkEditListFilters/BulkEditListFilters.js
src/hooks/useLocationFilters.js

"Preview of record changed" and filename disappear after resetting filters on "Logs" tab
https://issues.folio.org/browse/UIBULKED-291
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of …

UIBULKED-291: "Preview of record changed" and filename disappear after resetting filters on "Logs" tab

---

CHANGELOG.md
src/components/BulkEditList/BulkEditListResult/BulkEditListResult.test.js
src/components/BulkEditList/BulkEditListResult/PreviewContainer/PreviewContainer.js

Landing page is not cleared switching to "Query" tab after completed Bulk edit
[UIBULKED-289](https://issues.folio.org/browse/UIBULKED-289)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of …

UIBULKED-289: Landing page is not cleared switching to "Query" tab after completed Bulk edit

---

CHANGELOG.md
src/components/BulkEditList/BulkEditListFilters/FilterTabs/FilterTabs.js

Based on https://issues.folio.org/browse/UIBULKED-351 we need temporarly hide Query tab …

UIBULKED-351 Hide Query tab

---

CHANGELOG.md
src/components/BulkEdit.test.js
src/components/BulkEditList/BulkEditListFilters/FilterTabs/FilterTabs.js

https://issues.folio.org/browse/UIBULKED-351
Wrong tab was hided by mistake. CHANGELOG was updated in initial PR. 
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …

UIBULKED-351 Hide Query tab - fix

---

CHANGELOG.md
src/components/BulkEditActionMenu/BulkEditActionMenu.js
src/components/BulkEditList/BulkEditListResult/BulkEditInAppPreviewModal/BulkEditInAppPreviewModal.js
src/components/BulkEditLogs/BulkEditLogsActions/BulkEditLogsActions.js
src/hooks/api/useFileDownload.js

After this PR merged then triggering download file in one place will not impact other places. 
[UIBULKED-354](https://issues.folio.org/browse/UIBULKED-354)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as …

UIBULKED-354 Two identical files with the preview of proposed changes are downloaded from Logs

---

src/components/BulkEditList/BulkEditListResult/BulkEditInAppPreviewModal/BulkEditInAppPreviewModal.js

[IBULKED-372](https://issues.folio.org/browse/UIBULKED-372)
In this PR we changed `prefix` for preview in modal, since `step` from url that was used before was the same for editing `in app`

UIBULKED-372: Bulk edit - Element IDs are not unique.

---

CHANGELOG.md
src/components/BulkEditList/BulkEditListResult/BulkEditInApp/ContentUpdatesForm/ValuesColumn.js

[UIBULKED-378](https://issues.folio.org/browse/UIBULKED-378)
Here we make the button `commit changes` disabled when in `LocationSelection` selected `placeholder`. Previously it was available to commit changes with placeholder selected.
https://github.com/folio-org/ui-bulk-edit/assets/72550466/3697f197-944a-4f32-829d-1e8aab5af148

UIBULKED-378: "Select location" can be selected for item's location, and the "Confirm changes" button will remain active.

---

CHANGELOG.md
translations/ui-bulk-edit/en.json

[UIBULKED-376](https://issues.folio.org/browse/UIBULKED-376)
Here we just added translation keys and translations for them. The whole logic for building those columns was implemented early.

UIBULKED-376: Separate Item circulation notes in different columns

---

CHANGELOG.md
src/components/BulkEditList/BulkEditListResult/BulkEditInApp/BulkEditInApp.js
src/components/BulkEditList/BulkEditListResult/BulkEditInApp/ContentUpdatesForm/helpers.js
src/constants/selectOptions.js
translations/ui-bulk-edit/en.json

Provided the Staff suppress option on the bulk edit form for instance records. Ref [UIBULKED-390](https://issues.folio.org/browse/UIBULKED-390)
Test coverage will be increased in [UIBULKED-389](https://issues.folio.org/browse/UIBULKED-389), because main functionality is here.

UIBULKED-390 Add Staff suppress option to Instance records edits

---

src/constants/selectOptions.js

Add missed placeholder for instance options. Ref: [UIBULKED-390](https://issues.folio.org/browse/UIBULKED-390)

UIBULKED-390 add placeholder to instance options

---

src/components/BulkEditList/BulkEditListResult/BulkEditInApp/ContentUpdatesForm/ValuesColumn.test.js
src/components/BulkEditList/BulkEditListResult/Preview/ErrorsAccordion/ErrorsAccordion.js
src/components/BulkEditList/BulkEditListResult/Preview/ErrorsAccordion/ErrorsAccordion.test.js
src/components/BulkEditList/BulkEditListResult/Preview/Preview.css
src/components/BulkEditList/BulkEditListResult/Preview/Preview.js
src/components/BulkEditList/BulkEditListResult/Preview/PreviewAccordion/PreviewAccordion.js
src/utils/sortAlphabetically.js
test/jest/__mock__/index.js
test/jest/__mock__/resizeObserver.mock.js

Currently, all previews (errors and matched elements) were limited to 40% of the available viewport height. This is not entirely correct, after this PR we will have:
- if there are only errors, then it takes up the entire available height
- if only the record preview, it occupies the entire available height
- if both, the free space is divided in half between them
Please see attached images:
Only errors
Only preview of records
Preview of records + errors

UIBULKED-338 Add calculation of previews height based on content

---

package.json
src/components/BulkEditList/BulkEditListFilters/BulkEditListFilters.js
translations/ui-bulk-edit/en.json

In scope of https://github.com/folio-org/ui-bulk-edit/pull/461 adding permissions was missed. Also it's required clean state between tab changes, to avoid invalid parameters to query-builder.

UIBULKED-403 add missed permissions and clean state between tabs change

---

CHANGELOG.md
src/components/BulkEditList/BulkEditListFilters/BulkEditListFilters.js
src/components/BulkEditList/BulkEditListResult/Preview/Preview.js
src/components/BulkEditLogs/BulkEditLogsActions/BulkEditLogsActions.js
src/utils/getFileName.js
src/utils/getFileName.test.js
translations/ui-bulk-edit/en.json

In scope of [UIBULKED-367](https://issues.folio.org/browse/UIBULKED-367) it's required rename uploaded files name based on specific format (only for query approach)

UIBULKED-367 Logs - Provide a link to file with identifiers of the records affected by query

---

src/components/BulkEditList/BulkEditListResult/Preview/ElectronicAccessTable/ElectronicAccessTable.js
src/components/BulkEditList/BulkEditListResult/Preview/ElectronicAccessTable/ElectronicAccessTable.test.js

In scope of BE ticket [MODEXPW-457](https://folio-org.atlassian.net/browse/MODEXPW-457), delimiters for string was changed. Frontend have to be updated as well.
After changes everything is working as expected:

UIBULKED-384 Change delimiters to split string

---

CHANGELOG.md
src/components/BulkEditActionMenu/BulkEditActionMenu.test.js
src/components/BulkEditList/BulkEditList.test.js
src/components/BulkEditList/BulkEditListResult/BulkEditInApp/ContentUpdatesForm/AdditionalActionParameters.test.js
src/components/BulkEditList/BulkEditListResult/BulkEditInApp/ContentUpdatesForm/ValuesColumn.test.js
src/components/BulkEditList/BulkEditListResult/BulkEditInAppPreviewModal/BulkEditInAppPreviewModal.test.js
src/components/BulkEditList/BulkEditListResult/BulkEditListResult.test.js
src/components/BulkEditList/BulkEditListResult/BulkEditManualUploadModal/BulkEditManualUploadModal.test.js
src/components/BulkEditList/BulkEditListResult/Preview/ElectronicAccessTable/ElectronicAccessTable.test.js
src/components/BulkEditList/BulkEditListResult/Preview/ErrorsAccordion/ErrorsAccordion.test.js
src/components/PermissionsModal/PermissionsModal.test.js

https://folio-org.atlassian.net/browse/UIBULKED-408
Here we updated tests, added test cases using aXe.

UIBULKED-408: Bulk edit - Add accessibility testing to automated tests

---

src/components/BulkEditList/BulkEditList.js
src/components/BulkEditList/BulkEditListResult/BulkEditInApp/BulkEditInApp.js

Update search params to unified to avoid execution of getting action notes only on identifier tab (we also need it no query tab)

UIBULKED-411 Call action notes request on identifier and query tabs

---

src/components/BulkEditList/BulkEditListSidebar/LogsTab/LogsTab.js

Prevent reset of identifier when clicking "Reset all" button on logs tab.

UIBULKED-411 Prevent reset of identifier

---

CHANGELOG.md
src/constants/selectOptions.js

https://folio-org.atlassian.net/browse/UIBULKED-43
We hided `ISBN` and `ISNN` options from select

UIBULKED-437: Remove ISBN and ISSN from the list of instance records identifiers drop-down

---

CHANGELOG.md
src/components/BulkEditPane/BulkEditListSidebar/QueryTab/QueryTab.js

https://folio-org.atlassian.net/browse/UIBULKED-453
We added recently added prop to `plugin` to make the button `run query` disabled if `test query` returned an empty result

UIBULKED-453: Disable "run query" button if test query has not results

---

CHANGELOG.md
src/components/BulkEditPane/BulkEditListResult/BulkEditInApp/BulkEditInApp.css
src/components/BulkEditPane/BulkEditListResult/BulkEditInApp/ContentUpdatesForm/ActionsRow.js
src/components/BulkEditPane/BulkEditListResult/BulkEditInApp/ContentUpdatesForm/ContentUpdatesForm.js
src/components/BulkEditPane/BulkEditListResult/BulkEditInApp/ContentUpdatesForm/ValuesColumn.js

In scope of this PR was added first part of enhancements related to bulk-edit in-app form:
- added borders between columns
- added `dirty` property, to hightlight filled fields
Refs: [UIBULKED-441](https://folio-org.atlassian.net/browse/UIBULKED-441)
Before 
After (borders and dirty fields are present)

UIBULKED-441 Bulk edit form enhancements - part 1

---

CHANGELOG.md
src/components/BulkEditActionMenu/BulkEditActionMenu.js
src/components/BulkEditPane/BulkEditPane.js
src/hooks/api/useFileDownload.js
src/hooks/index.js

After this PR is merged, we will fix the problem where when downloading large files/when the Internet is slow, and user close the Action menu before content downloads - then the file will still be downloaded, since the save handler has been raised to a higher level.
Ref:  [UIBULKED-467](https://folio-org.atlassian.net/browse/UIBULKED-467)

UIBULKED-467 File is not downloaded to local machine when "Actions" menu is closed

---

src/components/BulkEditPane/BulkEditListSidebar/IdentifierTab/IdentifierTab.js
src/components/BulkEditPane/BulkEditListSidebar/QueryTab/QueryTab.js
src/components/BulkEditPane/BulkEditPane.js
src/components/shared/ProgressBar/ProgressBar.js
src/components/shared/ProgressBar/ProgressBar.test.js
src/hooks/useResetAppState.js

https://folio-org.atlassian.net/browse/UIBULKED-472
Here we removed logic based on `state` and made it based on `query params` for `ProgressBar.js`

UIBULKED-472: "Uploading" is displayed instead of "Committing" on Confirmation screen if to reload the page

---

CHANGELOG.md
src/components/BulkEditPane/BulkEditListResult/BulkEditInApp/BulkEditInApp.js
src/components/BulkEditPane/BulkEditListResult/BulkEditInApp/ContentUpdatesForm/ContentUpdatesForm.js

After this PR merged all fields will have unique ids what will prevent reset state after mount, if action name wasn't changed. Refs: [UIBULKED-470](https://folio-org.atlassian.net/browse/UIBULKED-470)
Before remove
After remove item in repetable fields, checkbox is still checked (in prev implementation it was reseted)

UIBULKED-470 "Apply to all holdings records", "Apply to all items records" checkboxes set to default value when delete other row

---

src/components/BulkEditPane/BulkEditListResult/BulkEditInApp/ContentUpdatesForm/helpers.js
src/components/BulkEditPane/BulkEditListResult/BulkEditInApp/ContentUpdatesForm/helpers.test.js
src/constants/actionParameters.js

In scope op PR https://github.com/folio-org/ui-bulk-edit/pull/520 supporting for checkin and checout notes weren't added.

UIBULKED-458 Show staff only checkbox for checkin/checkout notes

---

CHANGELOG.md
src/components/BulkEditPane/BulkEditListSidebar/LogsTab/LogsTab.js
src/utils/helpers.js

After this PR merget, Selection component will filter as `includes` instad of `starts with`

UIBULKED-479 Extend User search in User lookup

---

CHANGELOG.md
src/constants/inAppActions.js
translations/ui-bulk-edit/en.json

After this PR merged, "Find (full field search)" action will be changed to "Find" for Email type. Refs https://folio-org.atlassian.net/browse/UIBULKED-493
in the same time for all other places names weren't changed

UIBULKED-493 Rename "Find (full field search)" to "Find" for bulk edit Email in Users record type

---

CHANGELOG.md
src/components/BulkEditPane/BulkEditListResult/BulkEditInApp/ContentUpdatesForm/ActionsRow.js
src/components/BulkEditPane/BulkEditListResult/BulkEditInApp/ContentUpdatesForm/ValuesColumn.js
src/utils/sortAlphabetically.js
src/utils/sortAlphabetically.test.js

https://folio-org.atlassian.net/browse/UIBULKED-496
Here we add alphabetical ordering for `patron groups` in bulk edit in the app form
https://github.com/folio-org/ui-bulk-edit/assets/72550466/f65d0a29-3327-451a-a2d5-2c38f6284b6e

UIBULKED-496: Sorting patron groups list on bulk edit form

---

CHANGELOG.md
src/utils/getFileName.js

https://folio-org.atlassian.net/browse/UIBULKED-468
Here we added a new mapping for file name building in `Logs` tab.

UIBULKED-468: Query - File with errors encountered during the record matching is downloaded in .txt format with wrong name from Logs tab

---

CHANGELOG.md
src/components/BulkEditPane/BulkEditListSidebar/LogsTab/LogsTab.js

https://folio-org.atlassian.net/browse/UIBULKED-504
Here we pass additional fields in `getFullName` function to work with all fields from `user` object

UIBULKED-504: Names under "User" dropdown are consistent with the names in "Run by" column on "Bulk edit logs" page

---

src/components/BulkEditPane/BulkEditListResult/BulkEditInApp/ContentUpdatesForm/ContentUpdatesForm.js
src/components/BulkEditPane/BulkEditListResult/BulkEditInApp/ContentUpdatesForm/helpers.js
src/constants/selectOptions.js
src/utils/helpers.js
src/utils/helpers.test.js

After updating of Selection component, custom filter was updated to support filtering inside groups. Refs [UIBULKED-440](https://folio-org.atlassian.net/browse/UIBULKED-440)
Also in scope:
- update list height
- add missed placeholder in type select

UIBULKED-440 Update custom filter to support groups 

---

CHANGELOG.md
src/components/BulkEditPane/BulkEditListSidebar/LogsTab/LogsTab.js
src/constants/core.js
src/hooks/api/useBulkOperationUsers.js
src/hooks/api/useBulkOperationUsers.test.js

https://folio-org.atlassian.net/browse/UIBULKED-489
Here we changed logic of getting related users based on selected record types

UIBULKED-489: "User" dropdown doesn't include Users that did bulk edit of ONLY Instance record type

---

CHANGELOG.md
src/components/BulkEditActionMenu/BulkEditActionMenu.js

https://folio-org.atlassian.net/browse/UIBULKED-488
Here we add a condition to check if the user comes from an ESC environment to hide the action button for `local bulk-edit`

UIBULKED-488: Bulk edit of user records in local mode (CSV approach) is not supported in Query search

---

CHANGELOG.md
src/components/shared/ListSelect/ListSelect.js
src/constants/selectOptions.js

https://folio-org.atlassian.net/browse/UIBULKED-515
Here we added logic of hiding some options on `ESC` environment for` central tenant `.

UIBULKED-515: Limit identifiers options for holdings and items in ECS environment on Central tenant.

---

CHANGELOG.md
package.json
src/hooks/api/useRecordTypes.js

The response of `mod-fqm-manager`’s `/entity-types` is changed such that it now includes an additional property for the current FQL version. As such, `ui-bulk-edit` needs to be updated to handle more than just the previous simple array.
Additionally, we are adding a dependency on the current `entity-types` interface version, as it seems to have been omitted.

[UIBULKED-536] Support new entity-types response format

---

.github/workflows/build-npm.yml
src/components/BulkEditPane/BulkEditListSidebar/IdentifierTab/IdentifierTab.js
translations/ui-bulk-edit/en.json

https://folio-org.atlassian.net/browse/UIBULKED-526
Fix for existing implementation. Here we removed the default error since it is handled in the `useErrorMessage` hook. Also, we updated the translation to correct errors when the uploaded file is empty.

UIBULKED-526: Localize S3 error messages

---

src/components/BulkEditPane/BulkEditListResult/BulkEditInApp/BulkEditInApp.test.js
src/hooks/api/useHoldingsNotesEsc.js
src/hooks/api/useItemNotesEsc.js

https://folio-org.atlassian.net/browse/UIBULKED-524
Here small fix for existing implementation. We added `limit` for `notes` requests

UIBULKED-524: Localize Item's and Holdings' Notes names in ECS

---

CHANGELOG.md
src/components/BulkEditPane/BulkEditListResult/BulkEditInAppPreviewModal/BulkEditPreviewModalList.js
translations/ui-bulk-edit/en.json

https://folio-org.atlassian.net/browse/UIBULKED-538
Here we add the error on the preview modal for `Instance Marc` records for the more user-friendly error.

UIBULKED-538: “Are you sure" form notification banner wording for the case of bulk editing MARC fields for FOLIO Instances

---

CHANGELOG.md
src/components/BulkEditActionMenu/ActionMenuGroup/ActionMenuGroup.css
src/components/BulkEditActionMenu/BulkEditActionMenu.js
src/components/BulkEditActionMenu/BulkEditActionMenu.test.js
translations/ui-bulk-edit/en.json

https://folio-org.atlassian.net/browse/UIBULKED-542
Here we removed `menu group` from the action menu

UIBULKED-542: Remove "Actions" Header from Actions menu

---

src/components/BulkEditPane/BulkEditListResult/BulkEditMark/validation.js
src/components/BulkEditPane/BulkEditListResult/BulkEditMark/validation.test.js
src/components/BulkEditPane/BulkEditPane.css

https://folio-org.atlassian.net/browse/UIBULKED-539
Here is a small fix for the existing validation process for `additional subfield`

UIBULKED-539: Handle validation cases for “In.1“, “In.2“, "Subfield"  fields on Bulk edit MARC fields form

---

src/components/BulkEditPane/BulkEditListResult/BulkEditInApp/ContentUpdatesForm/ContentUpdatesForm.js

https://folio-org.atlassian.net/browse/UIBULKED-497
Here is the small fix of addicting `tenants` in the `option` object

UIBULKED-497: "Are you sure" preview displays outdated values after User changed selection on bulk edit form and clicked "Confirm changes"

---

src/components/BulkEditPane/BulkEditListResult/BulkEditInApp/ContentUpdatesForm/ContentUpdatesForm.js
src/components/BulkEditPane/BulkEditListResult/BulkEditInAppPreviewModal/BulkEditPreviewModal.js
src/components/BulkEditPane/BulkEditListResult/BulkEditInAppPreviewModal/BulkEditPreviewModalList.js
src/hooks/useConfirmChanges.js
src/hooks/useConfirmChanges.test.js
src/utils/pollForStatus.js
src/utils/pollForStatus.test.js

https://folio-org.atlassian.net/browse/UIBULKED-497
Fix for polling logic

UIBULKED-497: "Are you sure" preview displays outdated values after User changed selection on bulk edit form and clicked "Confirm changes" (follow-up)

---

src/components/BulkEditPane/BulkEditListResult/BulkEditInApp/ContentUpdatesForm/ValuesColumn.js

https://folio-org.atlassian.net/browse/UIBULKED-575
Here is the small fix for API calls, to prevent useless calls

UIBULKED-575: "Something went wrong" toast notifications when starting bulk edit (follow-up)

---

CHANGELOG.md
package.json

The real work is being done in https://github.com/folio-org/ui-plugin-query-builder/pull/180; this just adds the new permission required by the query builder.
We need access to `mod-configuration` to retrieve the tenant locale information, as this is not made available by Stripes (Stripes exposes either the tenant locale, or the user locale if one is set, but not both). `mod-fqm-manager` is not aware of user timezones, so queries will always be built with regard to tenant timezone.

[UIPQB-126] Use tenant timezone for building queries

---

src/components/BulkEditProfiles/BulkEditProfileDetails.js

https://folio-org.atlassian.net/browse/UIBULKED-661
> Scenario 5: Viewing Locked Profile  - Unauthorized user
> Given I have the permission required viewing or updating profiles but not for locking and unlocking bulk edit profiles
When I view an existing profile from Settings → Bulk Edit → [Record Type]s bulk edit profiles or I create a new profile
Then I see Lock profile checkbox selected and the checkbox is read only AND Action menu does not contain option for editing or deleting profile. The profile can only be duplicated.

UIBULKED-661 Hide 'Edit' action for locked profiled from unauthorized user
